alias pashi='cd /home/krg85/Projects/pashi'
alias pashi-core='cd /home/krg85/Projects/pashi/pashi-dsl-backend'
alias consultproj='cd /home/krg85/Projects/consulting-calculator'
alias consultproj='cd /home/krg85/Projects/consulting-calculator'
alias consultproj='cd /home/krg85'
alias pashi-lib-user='cd /home/krg85/Projects/golang/src/lib_user'
alias emserver='/usr/bin/emacs'
alias ssh='TERM='xterm-256color' ssh'
alias pashi-ssh='ssh -t dell@1.tcp.in.ngrok.io -p 22262 "cd /home/dell/dev/pashi/src/pashi-dsl-backend; bash --login"'
alias gsoft='git reset HEAD'
alias ghard='git reset --hard HEAD'
alias cat='bat'
